FROM centos:7.5.1804

# locale
RUN localedef -i ja_JP -f UTF-8 ja_JP.UTF-8
RUN echo 'LANG="ja_JP.UTF-8"' >  /etc/locale.conf
ENV LANG ja_JP.UTF-8

# Java
WORKDIR /tmp
COPY jre/jre-8u181-linux-x64.rpm ./
RUN yum -y localinstall ./jre-8u181-linux-x64.rpm

ENV JAVA_HOME /usr/java/default
ENV JAVA_VERSION 8u181

# Tomcat
ADD tomcat/apache-tomcat-8.5.32.tar.gz /usr/local

ENV TOMCAT_VERSION 8.5.32
ENV CATALINA_HOME /usr/local/apache-tomcat-8.5.32
ENV PATH ${CATALINA_HOME}/bin;${PATH}

# PROG
COPY tomcat/conf/context.xml ${CATALINA_HOME}/conf/context.xml
COPY tomcat/conf/server.xml ${CATALINA_HOME}/conf/server.xml
COPY tomcat/endorsed/*.jar ${CATALINA_HOME}/endorsed/
COPY tomcat/lib/*.jar ${CATALINA_HOME}/lib/
COPY tomcat/shared/lib/*.jar ${CATALINA_HOME}/shared/lib/
COPY tomcat/webapps/web-app.war ${CATALINA_HOME}/webapps/web-app.war
COPY tomcat/webapps/web-sample.war ${CATALINA_HOME}/webapps/web-sample.war

# Tomcat start up
EXPOSE 8080
CMD ${CATALINA_HOME}/bin/catalina.sh run
